version: '3.7'

services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: workshop
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./kafka-connect/init.sql:/docker-entrypoint-initdb.d/init.sql

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:5.2.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1

  kafka-connect:
    build:
      context: ./kafka-connect
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8083:8083
      - 9993:9993
    depends_on:
      - kafka1
    healthcheck:
      test: ["CMD", "curl", "localhost:8083"]
      interval: 2s
      timeout: 5s
      retries: 50
    environment:
      CONNECT_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "ddp_kafka_connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "_ddp_connect_config"
      CONNECT_OFFSET_STORAGE_TOPIC: "_ddp_connect_offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "_ddp_connect_status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      KAFKA_JMX_HOSTNAME: kafka-connect
      KAFKA_JMX_PORT: 9993

